// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqgrfHnXOjXTCAQ5kQh6QPjmoPEjbAlCA',
    appId: '1:870454415942:web:21a0814058583accdfb047',
    messagingSenderId: '870454415942',
    projectId: 'pingokart-712fc',
    authDomain: 'pingokart-712fc.firebaseapp.com',
    storageBucket: 'pingokart-712fc.appspot.com',
    measurementId: 'G-YNRQ0G3YHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkEzhAArcGpcCm5u-uLHrTtjIfK-DlYJg',
    appId: '1:870454415942:android:eac96b80c3cb6b42dfb047',
    messagingSenderId: '870454415942',
    projectId: 'pingokart-712fc',
    storageBucket: 'pingokart-712fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV9vl9AcclTFZYGWnd5kibK4dM3jNBzOo',
    appId: '1:870454415942:ios:4e5da3d28d33c9c7dfb047',
    messagingSenderId: '870454415942',
    projectId: 'pingokart-712fc',
    storageBucket: 'pingokart-712fc.appspot.com',
    iosBundleId: 'com.example.pingokart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV9vl9AcclTFZYGWnd5kibK4dM3jNBzOo',
    appId: '1:870454415942:ios:4e5da3d28d33c9c7dfb047',
    messagingSenderId: '870454415942',
    projectId: 'pingokart-712fc',
    storageBucket: 'pingokart-712fc.appspot.com',
    iosBundleId: 'com.example.pingokart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqgrfHnXOjXTCAQ5kQh6QPjmoPEjbAlCA',
    appId: '1:870454415942:web:f11803817ab3424bdfb047',
    messagingSenderId: '870454415942',
    projectId: 'pingokart-712fc',
    authDomain: 'pingokart-712fc.firebaseapp.com',
    storageBucket: 'pingokart-712fc.appspot.com',
    measurementId: 'G-XFNK8GTCW1',
  );

}